hetic_student_type:
    resource: "@HeticBundle/Controller/StudentTypeController.php"
    type:     annotation

hetic_student:
    resource: "@HeticBundle/Controller/StudentController.php"
    type:     annotation

bunker:
    resource: "@BunkerBundle/Controller/"
    type:     annotation
    prefix:   /

hetic_chevalier:
    resource: "@HeticBundle/Controller/chevalierController.php"
    type:     annotation

hetic:
    resource: "@HeticBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@HeticBundle/Controller/"
    type:     annotation
