<?php

namespace HeticBundle\Repository;

/**
 * ChevalierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChevalierRepository extends \Doctrine\ORM\EntityRepository
{
}
