<?php

namespace HeticBundle\Repository;

/**
 * StudentTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
