hetic_chevalier:
    resource: "@HeticBundle/Controller/chevalierController.php"
    type:     annotation

hetic:
    resource: "@HeticBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@HeticBundle/Controller/"
    type:     annotation
