<?php

namespace HeticBundle\Repository;

/**
 * CreatureFantastiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreatureFantastiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
