<?php

namespace HeticBundle\Repository;

/**
 * chevalierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class chevalierRepository extends \Doctrine\ORM\EntityRepository
{
}
